export default {
  CHANGE_MIN_PRICE: 'CHANGE_MIN_PRICE',
  CHANGE_MAX_PRICE: 'CHANGE_MAX_PRICE',
  CHANGE_CHECKED_BRANDS: 'CHANGE_CHECKED_BRANDS',
  CHANGE_CHECKED_IS_NEW: 'CHANGE_CHECKED_IS_NEW',
  CHANGE_CHECKED_IS_PROMO: 'CHANGE_CHECKED_IS_PROMO',
  SET_QUERY: 'SET_QUERY',
};
